version: "3"

services:

  poll:
    build: ./poll
    ports: 
      - "5000:80"
    networks: 
      - poll-tier
    environment:
      - host=redis
      - development
    restart: on-failure

  redis:
    image: redis
    networks: 
        - poll-tier
        - back-tier
    ports : 
        - "6379"
    restart: on-failure

  worker:
   build: ./worker
   networks: 
        - back-tier
   environment:
        - host_redis=redis
        - host_db=db
   restart: on-failure

  db:
    image: postgres
    networks: 
        - result-tier
        - back-tier
    environment:
        - development
    volumes:
        - db-data:/var/lib/postgresql/data
        
  result:
    build: ./result
    ports: 
      - "5001:80"
      - "5858:5858"
    networks:
      - result-tier
    environment:
      - host=db
    restart: on-failure

networks:
    poll-tier:
    result-tier:
    back-tier:

volumes:
    db-data: